# Server configuration
server:
  port: 7080

# ===================================================================
# spring配置
# ===================================================================
spring:
  jpa:
    database: mysql
    show-sql: true  #显示执行sql
    hibernate:
      ddl-auto: update  # 数据库的表和列会自动创建

  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    url: jdbc:mysql://192.168.36.39:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Mysql@3306
    driver-class-name: com.mysql.jdbc.Driver

  jmx: # 必须关闭jms，否则启动报错
    enabled: false

# ===================================================================
# JWT配置
# ===================================================================
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"

# ===================================================================
# mybatis配置，包括分页插件配置如下
# ===================================================================
mybatis:
    type-aliases-package: com.qtdbp.api.model
    mapper-locations: classpath:mapper/*.xml
